### PR TITLE
BuildSourceImage.sh: quiet the output

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by vbatts** [comment]
now the output looks like:
```shell
[vbatts@knob BuildSourceImage]$ ./BuildSourceImage.sh -o ./output -s ./SRCRPMS/
[SrcImg][INFO] calling source collection drivers
[SrcImg][INFO]  --> context_dir
[SrcImg][INFO]  --> extra_src_dir
[SrcImg][INFO]  --> rpm_dir
[SrcImg][INFO]  --> rpm_fetch
[SrcImg][INFO] packed 'oci:/home/vbatts/src/github.com/containers/BuildSourceImage/SrcImg/tmp/SrcImg.z3HxHN:latest-source'
[SrcImg][INFO] succesfully packed 'oci:/home/vbatts/src/github.com/containers/BuildSourceImage/SrcImg/tmp/SrcImg.z3HxHN:latest-source'
[SrcImg][INFO] copied to oci:./output:latest-source
```

**Comment by rhatdan** [comment]
LGTM

**Comment by vbatts** [comment]
hopefully fixed CI. PTAL

**Comment by vrothberg** [comment]
Green green green :green_heart:

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
