### PR TITLE
Cirrus: Add placeholder configuration

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@vrothberg well dang, I still don't see the settings (gear) icon on https://cirrus-ci.com/github/containers/BuildSourceImage :confused:

**Comment by vbatts** [comment]
but it seems to have run ...

**Comment by cevich** [comment]
ya, I don't get it.  Seems like a permissions problem, but I thought I checked all those places :confounded:

**Comment by cevich** [comment]
Even tried adding myself as an admin collaborator to the repo (I already have admin on the org.), still no dice.  I hate to say we might need to merge this PR before the button will show up, I can't find any proof of that though.  I see the button on all other repos (in cirrus).

**Comment by cevich** [comment]
Yeah, even after reviewing the documentation it does say the file needs to be pushed.  I couldn't find any direct mention of it being required to access settings though.  I suggest we merge this and see.  If it works, I'll update our internal docs to mention this.

**Comment by vrothberg** [comment]
The fact that Travis fails is reinforcing my desire of moving to Cirrus :-)
Thanks for your help, @cevich!

**Pull request merged**
