### PR TITLE
Identify and create source image

### PR DESCRIPTION
**Pull request by lcarva**
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

### CODE REVIEW

**Comment by lcarva** [comment]
Note: I didn't add the ability to add a "context" and "additional sources" dirs because the user can always do that with the system tools. I envision this would be used as such:
```bash
$ build-source-image identify fedora:29 sources
$ cp ~/src/containers/fedora sources/context
$ cp ~/src/foo/extra sources/extra
...
$ build-source-image create fedora:29-src
```

**Comment by rhatdan** [comment]
I made some changes to the bash version of this, to set the EPOCH of the files to 0.
```
    echo "Adding $i"
    touch --date='@0' $i
    buildah add --add-history ${SRC_CTR} $i /RPMS
    export IMG=$(buildah commit --rm ${SRC_CTR} $i)
    export SRC_CTR=$(buildah from ${IMG})
```

**Comment by rhatdan** [comment]
@lcarva The bash script has evolved a lot since this python code was written, could you update the python to match the bash?

**Comment by lcarva** [comment]
> @lcarva The bash script has evolved a lot since this python code was written, could you update the python to match the bash?

Time has been scarce :/ 
I might have some time next week.

**Comment by vbatts** [comment]
lets close this one

**Pull request closed without merging**
