### PR TITLE
*: remove building from a remote image reference

### PR DESCRIPTION
**Pull request by vbatts**
This internally used skopeo to fetch a remote image, which had design
issues with how to handle auth.

Now the recommendation is to:
* directly use skopeo to fetch `skopeo copy docker://... oci:./...`
* unpack the image layout `./BuildSourceImage.sh ./src/ ./dest`
* TODO pass this `./dest/` relative-root to the downloader plugin?
* then build as usual from this content

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
I wonder if we need the same for pushing?

**Comment by vbatts** [comment]
For sure. I did have a branch that ripped it all out in one go, but it got
a bit messed up, so I'm going piecemeal. I could just make this a wip PR
for all of it, and layer commit at a time for each aspect. But that begins
looking like individual PRs anyways.

**Comment by vrothberg** [comment]
Sounds good to me, thanks @vbatts!

LGTM, @rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
