### PR TITLE
Update CI VM Images to F37

### PR DESCRIPTION
**Pull request by cevich**

### CODE REVIEW

**Comment by cevich** [comment]
@vrothberg when you have a chance, PTAL (low-priority).  My secret-decoder-ring predates the invention of these tests, it's of no use :frowning_face:

**Comment by cevich** [comment]
@vrothberg re-ping (I'm assuming you missed the first one).

**Comment by vrothberg** [comment]
> @vrothberg re-ping (I'm assuming you missed the first one).

I did.  Thank you for the ping!  I will take a look ASAP

**Comment by vrothberg** [comment]
I cherry-picked your commit into https://github.com/containers/BuildSourceImage/pull/86, so we are good.  Thanks, @cevich !

**Pull request closed without merging**
