### PR TITLE
Re-license as GPLV2

### PR DESCRIPTION
**Pull request by rhatdan**
The code was originally licensed as GPL V3 and we thought that was
too restrictive, so we are lowering it to GPL V2

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg @vbatts Is this ok with you?

**Comment by vbatts** [comment]
@jnovy @nalind too

**Comment by vbatts** [comment]
LGTM

**Comment by vrothberg** [comment]
LGTM

**Comment by nalind** [comment]
LGTM

**Comment by jnovy** [comment]
LGTM

**Pull request merged**
